version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "14.30"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    groups:
      - name: "klips-chart-api"
        directory: "./easy-to-use-api/klips-chart-api"
      - name: "klips-url-generator"
        directory: "./easy-to-use-api/klips-url-generator"
      - name: "klips-timelapse-video-api"
        directory: "./easy-to-use-api/klips-timelapse-video-api"
      - name: "klips-api"
        directory: "./klips-api"
      - name: "error-handler"
        directory: "./worker/error-handler"
      - name: "rollback-handler"
        directory: "./worker/rollback-handler"
      - name: "geoserver-init"
        directory: "./geoserver-init"
