version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    groups:
      - name: "chart-api"
        directory: "./easy-to-use-api/klips-chart-api"
      - name: "video-api"
        directory: "./easy-to-use-api/klips-timelapse-video-api"
      - name: "url-generator"
        directory: "./easy-to-use-api/klips-url-generator"
