version: 2
updates:
  - package-ecosystem: "npm"
    directory: "./easy-to-use-api/klips-chart-api"
    schedule:
      interval: "daily"
      time: "14.48"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    labels:
      - "npm dependencies"
